Add set-default argument

diff --git a/k8-align b/k8-align
--- a/k8-align
+++ b/k8-align
@@ -3,10 +3,13 @@
 REPO_DIR_NAME="$(dirname "$0")" || exit 1
 SCRIPT_NAME="$(basename "$0")" || exit 1
 
+DEFAULT_DOCKER_IMAGE_FILE_NAME="${REPO_DIR_NAME}/default_docker_image_at_k8.txt"
+
 print_usage(){
   echo "USAGE: $0 run"
   echo "USAGE: $0 build --name <image-name>"
   echo "USAGE: $0 push --name <image-name>"
+  echo "USAGE: $0 set-default --name <image-name>"
   echo "USAGE: $0 version"
   echo "  <image-name> Name of the Docker image"
   exit 1
@@ -26,6 +29,13 @@ print_push_usage(){
   exit 1
 }
 
+print_set_default_usage(){
+  echo "Set Docker image as default image for runs."
+  echo "USAGE: $0 set-default --name <image-name>"
+  echo "  [-n/--name] Name of the Docker image (Required)"
+  exit 1
+}
+
 main() {
   if [ $# -lt 1 ]; then
    print_usage
@@ -41,6 +51,9 @@ main() {
      ;;
   run)
      run "$@"
+     ;;
+  set-default)
+     set_default "$@"
      ;;
   version)
      version "$@"
@@ -83,7 +96,7 @@ build() {
 
   echo "The build has succeeded."
   echo "If you want to push this image to GCP, run the following command:"
-  echo "$0 push --name ${name}"
+  echo "  $0 push --name ${name}"
 }
 
 push() {
@@ -118,11 +131,52 @@ push() {
   already_pushed=$(image_has_already_been_pushed "${name}")
 
   if [[ ${already_pushed} ]]; then
-    die "Image with ${name} has already been pushed to GCP. Please rebuild with a newer version of the image name.'"
+    die "Image with ${name} has already been pushed to GCP. Please rebuild with a newer version of the image name."
   else
     echo "Pushing new image ${name} to GCP"
     docker push "${name}" || die "Failed Docker push"
     echo "Pushed new image ${name} to GCP"
+    echo "If you wish to set this image as the new default image, run the following command:"
+    echo "  $0 set-default --name ${name}"
+  fi
+}
+
+set_default() {
+  local UNRECOGNIZED=()
+  local key
+  while [[ $# -gt 0 ]]
+  do
+    key="$1" && shift
+    case $key in
+      -n|--name)
+        name="$1" && shift;;
+      *)
+        UNRECOGNIZED+=("${key}");;
+    esac
+  done
+
+  # sanity checks
+  local input_error=false
+  if [[ ! ${#UNRECOGNIZED[@]} -eq 0 ]]; then
+    print_error_msg "Unrecognized options to ${SCRIPT_NAME}: options=(${UNRECOGNIZED[*]})"
+    input_error=true
+  fi
+  if [[ -z ${name} ]]; then
+    print_error_msg "Variable 'name' has not been set"
+    input_error=true
+  fi
+  if [[ ${input_error} == true ]]; then
+    print_set_default_usage
+  fi
+
+  echo "Checking whether image with name '${name}' exists at GCP"
+  already_pushed=$(image_has_already_been_pushed "${name}")
+
+  if [[ ${already_pushed} ]]; then
+    set_default_docker_image_at_k8 "${name}" || die "Could not set Default Docker image"
+    echo "Default Docker image for runs has been set to ${name}"
+  else
+    die "Cannot set ${name} as default image since it does not exist at GCP."
   fi
 }
 
@@ -132,7 +186,7 @@ run() {
   local clean_pod_name
   clean_pod_name="$(echo "${pod_name}" | tr '_' '-' | tr '[:upper:]' '[:lower:]' | tr '.' '-')"
   local docker_image
-  docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default docker image name"
+  docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default Docker image name"
 
   # Make sure correct credentials are available
   gcloud container clusters get-credentials rerun-cluster --region europe-west4 --project hmf-crunch \
@@ -147,18 +201,24 @@ run() {
 
 version() {
   local default_docker_image
-  default_docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default docker image name"
+  default_docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default Docker image name"
   echo "Current default Docker image version at k8: ${default_docker_image}"
 }
 
 get_default_docker_image_at_k8() {
-  cat "${REPO_DIR_NAME}/default_docker_image_at_k8.txt"
+  cat "${DEFAULT_DOCKER_IMAGE_FILE_NAME}"
+}
+
+set_default_docker_image_at_k8() {
+  local name=$1 && shift
+  [[ -n ${name} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
+  echo "${name}" > "${DEFAULT_DOCKER_IMAGE_FILE_NAME}"
 }
 
 image_has_already_been_pushed() {
   local name=$1 && shift
   [[ -n ${name} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
-  docker manifest inspect "${name}" > /dev/null 2>&1
+  docker manifest inspect "${name}"
 }
 
 die() {
