Make error messages more clear

diff --git a/k8-align b/k8-align
--- a/k8-align
+++ b/k8-align
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 REPO_DIR_NAME="$(dirname "$0")" || exit 1
+SCRIPT_NAME="$(basename "$0")" || exit 1
 
 print_usage(){
   echo "USAGE: $0 build --name <image-name>"
@@ -40,13 +41,13 @@ build() {
       -n|--name)
         name="$1" && shift;;
       *)
-        UNRECOGNIZED+=("$1");;
+        UNRECOGNIZED+=("${key}");;
     esac
   done
   
   # sanity checks
-  [[ ${#UNRECOGNIZED[@]} -eq 0 ]] || die "Unrecognized options to ${SCRIPT_NAME}: options=${UNRECOGNIZED[*]}"
-  [[ -n ${name} ]] || die "Variable 'name' has not been set"
+  [[ ${#UNRECOGNIZED[@]} -eq 0 ]] || die_usage "Unrecognized options to ${SCRIPT_NAME}: options=(${UNRECOGNIZED[*]})"
+  [[ -n ${name} ]] || die_usage "Variable 'name' has not been set"
 
   docker build "${REPO_DIR_NAME}" -t "${name}" || die "Failed Docker build"
 }
@@ -78,6 +79,12 @@ get_default_docker_image_at_k8() {
 
 die() {
     echo "[ERROR] $1"
+    exit 1
+}
+
+die_usage() {
+    echo "[ERROR] $1"
+    print_usage
     exit 1
 }
 
